---
abstract: 'Implementation of UPS Online Tools API in Perl'
author:
  - 'Sherzod B. Ruzmetov <sherzodr@cpan.org>'
  - 'Gianni Ceccarelli <gianni.ceccarelli@net-a-porter.com>'
build_requires:
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  diagnostics: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-UPS
no_index:
  directory:
    - t/lib
requires:
  Carp: 0
  Class::Struct: 0.58
  File::Spec: 0
  IO::File: 0
  LWP::UserAgent: 0
  XML::Simple: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/NET-A-PORTER/Net-UPS.git
version: 0.05
